when:
    -   event: manual
        branch: main

steps:
    -   name: build-cacher
        image: woodpeckerci/plugin-docker-buildx
        settings:
            repo:
                from_secret: wp_registry_repo
            registry:
                from_secret: wp_registry
            tags:
                - latest
                - ${CI_COMMIT_SHA}
            dockerfile: ./YouTube.ServerSide.Cacher/Dockerfile
