when:
    -   event: manual
        branch: main

steps:
    -   name: build-cacher
        image: woodpeckerci/plugin-docker-buildx
        settings:
            repo: ${registry_url}/yt-cacher
            registry: ${registry_url}
            tags:
                - latest
                - ${CI_COMMIT_SHA}
            dockerfile: ./YouTube.ServerSide.Cacher/Dockerfile
        environment:
            registry_url:
                from_secret: CONF_WP_REGISTRY
